### PR TITLE
Use stream-combiner2

### PR DESCRIPTION
**Pull request by rjferguson21**

### CODE REVIEW

**Comment by OverZealous** [comment]
I'm going to push this out as a major change, only because I've had problems with streams 2 before.  Hopefully this won't cause the issues, but I don't want someone to run into unexpected changes accidentally.

**Comment by OverZealous** [comment]
OK, well, that was a mistake.  Completely broken my build process.  I guess I should have tested before I pushed it up.  :-)

**Comment by rjferguson21** [comment]
Yea, it seemed to fix my problem with the combined stream emitting `finish` events but when I integrated into my gulp build it broke as well.  I think it has something to do with not handling streams in `objectMode`.

`stream-combiner` seemed to handle that without specifying but it seems with `streams2` you have to set `{ objectMode: true }`.  Not sure how this needs to be handled considering that gulp plugins are outputting vinyl file objects, but I don't know if that would break things for non-gulp pipelines.

**Comment by OverZealous** [comment]
Ah.  Well, I can't look into it now (I was hoping this would fix an unrelated issue), but I'll keep this in mind if I get a chance to try again.

**Comment by erikkemperman** [comment]
@OverZealous 
I was looking into switching to streams 2 as well a while ago, forked this repository around the same time as @rjferguson21 and had a first go at it.

Have been distracted by lots of other things in the mean time, but I'd like to revisit this now. So I was just wondering if you guys happen to have any test cases handy that broke for you? Then I can see if I can make it work somehow.

**Comment by OverZealous** [comment]
@erikkemperman Sorry, I don't remember what broke exactly, but I'm pretty sure it's because `steam-combiner2` or `streams2`, you have to manually specify `objectMode`.

I don't really have a lot of free time right now to look into the details.

(Honestly, I don't understand why everyone pushes for streams 2 so hard—the streams themselves are not the bottleneck in _my_ build process.  Uglify & other data manipulation processes are orders of magnitude slower.)

**Comment by erikkemperman** [comment]
@OverZealous All right, fair enough! My fork is working for my little use case. If you're (still) interested in having something like this at some point, let me know and I can make a PR. No worries either way.

**Pull request merged**
